//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo03
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.Xml.Serialization;

    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
        //https://forums.asp.net/t/1782688.aspx?Cannot+serialize+member+xxx+of+type+System+Collections+Generic+ICollection+1+xxx+xxx+Version+1+0+0+0+Culture+neutral+PublicKeyToken+null+because+it+is+an+interface+
            //this.Products = new HashSet<Product>();
            this.Products = new List<Product>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        //public virtual ICollection<Product> Products { get; set; }
        //[XmlIgnore]
        //[IgnoreDataMember]
        public virtual List<Product> Products { get; set; }
        
    }
}
